// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XtramileWeather.Infrastructure.Persistence;

#nullable disable

namespace XtramileWeather.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922140701_SeedInitialLocations")]
    partial class SeedInitialLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("XtramileWeather.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Jakarta"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Bandung"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Surabaya"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "Melbourne"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Brisbane"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            Name = "Singapore"
                        });
                });

            modelBuilder.Entity("XtramileWeather.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SG",
                            Name = "Singapore"
                        });
                });

            modelBuilder.Entity("XtramileWeather.Domain.Entities.FavoriteCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.ToTable("FavoriteCities");
                });

            modelBuilder.Entity("XtramileWeather.Domain.Entities.City", b =>
                {
                    b.HasOne("XtramileWeather.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("XtramileWeather.Domain.Entities.FavoriteCity", b =>
                {
                    b.HasOne("XtramileWeather.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
